[package]
name = "plotlars"
version = "0.8.1"
authors = ["Alberto Cebada Aleu <contact@albertocebada.com>"]
edition = "2024"
rust-version = "1.86.0"
description = "Plotlars is a Rust library designed to facilitate the integration between the Polars data analysis library and visualization libraries."
documentation = "https://docs.rs/plotlars/latest/plotlars/"
readme = "README.md"
homepage = "https://github.com/alceal/plotlars"
repository = "https://github.com/alceal/plotlars"
license = "MIT"
keywords = ["chart", "plot", "plotly", "polars", "visualization"]
categories = ["visualization"]

[dependencies]
bon = "3.6.1"
image = "0.25.6"
indexmap = "2.9.0"
ordered-float = "5.0.0"
plotly = "0.12.1"
polars = { version = "0.46.0", features = ["lazy", "strings"] }
serde = "1.0.219"
serde_json = "1.0.140"
